from pptx import Presentation

def title_page(powerpoint, layout, title_text, subtitle_text):
    slide = powerpoint.slides.add_slide(layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]

    title.text = title_text
    subtitle.text = subtitle_text

def content_page(powerpoint, layout, title_text, content_text):
    slide = powerpoint.slides.add_slide(layout)
    title = slide.shapes.title
    content = slide.placeholders[1]

    title.text = title_text
    content.text = content_text

if __name__ == "__main__":
    powerpoint = Presentation()

    title = powerpoint.slide_layouts[0]
    content = powerpoint.slide_layouts[1]

    title_page(powerpoint, title, "Bond Analytics Report", "Generated by Python")
    content_page(powerpoint, content, "Bond Analytics", "This is a sample content page.")

    powerpoint.save("test_presentation.pptx")
    print("Complete")

